### ISSUE TITLE
Locally Decrypted GPG over SSH

### ISSUE THREAD

**Issue by stevesbrain** [dyne/Tomb#255] opened 2017-04-05 03:12 UTC
Hi all,

I have a scenario (like I'm sure some of us do) where my tombs themselves live on remote servers, and I would previously have to pipe my key over SSH like:

```bash
ssh my.other.server.net 'cat tomb.key' | tomb open -k - secrets.tomb 
```

Now, when switching to using an existing GPG key, the private key for that lives only on my YubiKey. This works great locally - but how can I go about decrypting this over SSH? The remote system has no access to the private key, and piping like:

```bash
gpg --decrypt tomb.key | tomb open -k - secrets.tomb
```

Does not work, of course. Has anyone else had any success in this same scenario, or have any suggestions? Thanks!

**Comment by jaromil** [comment] 2017-04-05 07:44
Hi! When you write "when switching to using an existing GPG key", do you mean a key that is asymmetrically encrypted using the new `-g` switch, recently implemented in our development version here by @roddhjav ?

**Comment by roddhjav** [comment] 2017-04-05 14:02
One of the first commit I did with the GPG support introduced a bug preventing to support of gpg encrypted tomb key loaded from stdin. This is fixed by 1050d43c596238630d22d545e6c8de26bdad0ef5

However, I have a few concerns regarding your ssh command. As I understand it, by `ssh my.other.server.net 'cat tomb.key' | tomb open -k - secrets.tomb` you get the tomb key from the server and use it on a tomb locally. I am wrong? This is not what you wrote.

I think a solution using `sshfs` as described [in the wiki](https://github.com/dyne/Tomb/wiki/Tombsshfs) is way better in terms of security.

**Comment by stevesbrain** [comment] 2017-04-06 23:56
@jaromil - Indeed, I am referring to the new ```-g``` switch :)

@roddhjav - Apologies if my description didn't quite match the command - I just quickly pulled the command from the reference doco. My key lives on my local machine, whilst the tomb lives on the server :) Whilst sshfs would be better in terms of security, I'd still be encountering the issue whereby I have to decrypt locally first (due to the way my keys work). I'll check out the latest commit and see how it goes for me! Thanks

**Comment by stevesbrain** [comment] 2017-04-07 00:05
So, I've tested it out just locally for the moment, however, unless I'm misunderstanding, it's not working as expected. The command:

```bash
tomb open -k help-gpg.key -g help.me
```

Does work as expected, prompting me for my GPG key password after I've inserted my YubiKey smartcard. However, using gpg to decrypt first, then piping it to tomb, does not work:

```bash
:: [stephen@duck] ~
$ gpg -d help-gpg.key | tomb open -k - help.me -g
tomb  .  Commanded to open tomb help.me
tomb  .  An active swap partition is detected...
tomb (*) The undertaker found that all swap partitions are encrypted. Good.
tomb  .  Valid tomb file found: help.me
tomb  .  Key encrypted with a GnuPG Key
gpg: encrypted with 2048-bit RSA key, ID XXXXXXXXXX, created 2015-05-11
      "KEYFILE <user@domain.com>"
tomb [W] The key seems invalid or its format is not known by this version of Tomb.
tomb [W] Attempting key recovery.
tomb  .  Mountpoint not specified, using default: /run/media/stephen/help
tomb (*) Opening help on /run/media/stephen/help
tomb  .  This tomb is a valid LUKS encrypted device.
tomb  .  Cipher is "aes" mode "xts-plain64:sha256" hash "sha256"
tomb [E] No valid password supplied.
```
Running the same without ```-g``` at the end just leads to it prompting for a passphrase as per its usual behaviour. Am I doing something wrong in this instance @roddhjav? Thanks!

**Comment by jaromil** [comment] 2017-04-07 06:53
I am sorry if this answer deludes you, but there are several flaws in your request to fix:
1) Tomb does not facilitate the transport of unencrypted keys on any medium, let alone the Internet
2) Your use-case is best covered by another script, a few lines should be enough to do what you need
3) I recommend you add one line to your command and download the key to a temporary directory then use -g
Therefore this is not a bug.

**Closed by jaromil** 2017-04-07 06:53 UTC

**Comment by roddhjav** [comment] 2017-04-07 09:38
@stevesbrain As @jaromil said, tomb is not intended to be used in this way. You can run 
```
cat help-gpg.key | tomb open -k - help.me -g
```
But not 
```
gpg -d help-gpg.key | tomb open -k - help.me -g
```

> My  key lives on my local machine, whilst the tomb lives on the server :) Whilst sshfs would be better in terms of security, I'd still be encountering the issue whereby I have to decrypt locally first (due to the way my keys work).

As far as I understand, you want to run tomb on the server itself. Meaning the server has the tomb script and decrypt your tomb `help.me` (also on the server) using the unencrypted key it receives through a ssh pipe. **It is a good think tomb *prevents* you of doing this because your server would know your secret key.** Therefore there would be no point of using encrypted storage at all.

The solution is to use [sshfs](https://github.com/dyne/Tomb/wiki/Tombsshfs). With sshfs you are using the local tomb "binary" to open locally a remote tomb that will stay encrypted and will leave no secret on the remote server. Moreover with sshfs you can use tomb as usual and therefore you won't have an issue with your smart card.
