### ISSUE TITLE
tomb slam all kills X server - lsof 4.90 bug in rolling releases

### ISSUE THREAD

**Issue by popsUlfr** [dyne/Tomb#310] opened 2018-03-14 08:47 UTC
Hello,

I've been having suspend troubles lately and it only occurred recently to check for my `tomb slam all` that executes on suspend which I have been using for a year already without problems, but now...

`/etc/systemd/system/tomb-suspend.service`
```
[Unit]
Description=Slam all tombs
Before=sleep.target

[Service]
Type=oneshot
ExecStart=-/usr/bin/tomb slam all

[Install]
WantedBy=sleep.target
```

The log output : 
```
systemd[1]: Starting TLP suspend/resume...
systemd[1]: Starting Slam all tombs...
sudo[27438]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/findmnt -rvo SOURCE,TARGET,FSTYPE,OPTIONS,LABEL
sudo[27438]: pam_unix(sudo:session): session opened for user root by (uid=0)
sudo[27438]: pam_unix(sudo:session): session closed for user root
tomb[27412]: tomb (*) Slamming tomb [sshkeys] mounted on /run/media/popsulfr/sshkeys
sudo[27459]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/lsof -t +D /run/media/popsulfr/sshkeys
sudo[27459]: pam_unix(sudo:session): session opened for user root by (uid=0)
systemd[1]: Started TLP suspend/resume.
sudo[27459]: pam_unix(sudo:session): session closed for user root
tomb[27412]: tomb  .  [sshkeys] sending TERM to root (::4 uid::)
sudo[27574]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/kill -TERM 881
sudo[27574]: pam_unix(sudo:session): session opened for user root by (uid=0)
klauncher[1159]: The X11 connection broke (error 1). Did the X11 server die?
sudo[27574]: pam_unix(sudo:session): session closed for user root
kdeinit5[1158]: kdeinit5: Fatal IO error: client killed
kdeinit5[1158]: kdeinit5: sending SIGHUP to children.
plasmashell[1225]: The X11 connection broke (error 1). Did the X11 server die?
```

Executing `tomb slam all` kills the whole desktop X included. I'll try older versions of tomb to see if it has the same behaviour. This is with Tomb 2.5.

EDIT:
I tested older releases and it's still the same. Seems like systemd or the kernel made changes on how lsof reports the processes using the mount points maybe ?
The funny thing is that even after the massacre, killing everything in sight, the tomb was still mounted.

`tomb close all` works well though in place of `tomb slam all` and successfully closes the tomb so I'm still thinking there's something wrong during the `slam` process ? The processes it thinks are using the mountpoint aren't actually preventing the tomb from closing.

I'll be using `tomb close all` for now but I need to remember to cd out of the directory or not use any files in it before suspending.

**Comment by jaromil** [comment] 2018-03-15 09:04
I can only add that I also experience what could possibly be regression issues using `lsof` across different kernels. I'd rather rule out `systemd` as the cause here, since I'm not using it, but still struggling with `lsof`. A good try in your situation would be to keep same setup and run an older kernel?

**Comment by popsUlfr** [comment] 2018-03-15 10:21
Hi @jaromil 

> A good try in your situation would be to keep same setup and run an older kernel?

I won't go back just for this one issue to be honest.

`fuser` seems to be more reliable for finding the processes that hold a lock on files on a mounted tomb : 
```
$ fuser -m <mountpoint> | xargs kill -SIGTERM
$ sleep 2
$ fuser -m <mountpoint> | xargs kill -SIGKILL
$ tomb close all
```
This takes care of closing the tombs from what I tested on my system. :D

**Comment by jaromil** [comment] 2018-03-15 10:43
ACK. Very interesting. I will also test it ASAP. Are you planning a PR yourself?

**Comment by Narrat** [comment] 2018-03-15 13:02
Please don't forget about #220

**Comment by jaromil** [comment] 2018-03-15 13:38
Right. I remember fuser being somewhere around Tomb sometimes. Would it make sense to have a switch for slam mode? Ideally we need some more testing on different documented situations.

**Comment by Narrat** [comment] 2018-03-15 20:31
Either fuser or lsof? Dunno. Ideally only one option is needed, but both has their flaws.

I notice the following with lsof-4.90, which is indeed weird

```sh
lsof +D /run/media/omnius/INTENSO 
COMMAND    PID   USER   FD   TYPE  DEVICE SIZE/OFF  NODE NAME
Xorg       440 omnius  mem    CHR   226,0          13684 /dev/dri/card0
Xorg       440 omnius   11u   CHR   226,0      0t0 13684 /dev/dri/card0
Xorg       440 omnius   12u   CHR   226,0      0t0 13684 /dev/dri/card0
Xorg       440 omnius   13u   CHR   226,0      0t0 13684 /dev/dri/card0
Xorg       440 omnius   14u   CHR   226,0      0t0 13684 /dev/dri/card0
Xorg       440 omnius   15u   CHR   226,0      0t0 13684 /dev/dri/card0
Xorg       440 omnius   17u   CHR   226,0      0t0 13684 /dev/dri/card0
termite    480 omnius  mem    CHR 226,128          13683 /dev/dri/renderD128
termite    480 omnius    4u   CHR 226,128      0t0 13683 /dev/dri/renderD128
termite    480 omnius    5u   CHR 226,128      0t0 13683 /dev/dri/renderD128
termite    480 omnius    6u   CHR 226,128      0t0 13683 /dev/dri/renderD128
termite    480 omnius   14u   CHR     5,2      0t0    22 /dev/ptmx
termite    481 omnius  mem    CHR 226,128          13683 /dev/dri/renderD128
termite    481 omnius    4u   CHR 226,128      0t0 13683 /dev/dri/renderD128
termite    481 omnius    5u   CHR 226,128      0t0 13683 /dev/dri/renderD128
termite    481 omnius    6u   CHR 226,128      0t0 13683 /dev/dri/renderD128
termite    481 omnius   14u   CHR     5,2      0t0    22 /dev/ptmx
termite    482 omnius  mem    CHR 226,128          13683 /dev/dri/renderD128
termite    482 omnius    4u   CHR 226,128      0t0 13683 /dev/dri/renderD128
termite    482 omnius    5u   CHR 226,128      0t0 13683 /dev/dri/renderD128
termite    482 omnius    6u   CHR 226,128      0t0 13683 /dev/dri/renderD128
termite    482 omnius   14u   CHR     5,2      0t0    22 /dev/ptmx
zsh        578 omnius    0u   CHR   136,0      0t0     3 /dev/pts/0
zsh        578 omnius    1u   CHR   136,0      0t0     3 /dev/pts/0
zsh        578 omnius    2u   CHR   136,0      0t0     3 /dev/pts/0
zsh        578 omnius   10u   CHR   136,0      0t0     3 /dev/pts/0
zsh        579 omnius    0u   CHR   136,1      0t0     4 /dev/pts/1
zsh        579 omnius    1u   CHR   136,1      0t0     4 /dev/pts/1
zsh        579 omnius    2u   CHR   136,1      0t0     4 /dev/pts/1
zsh        579 omnius   10u   CHR   136,1      0t0     4 /dev/pts/1
zsh        580 omnius    0u   CHR   136,2      0t0     5 /dev/pts/2
zsh        580 omnius    1u   CHR   136,2      0t0     5 /dev/pts/2
zsh        580 omnius    2u   CHR   136,2      0t0     5 /dev/pts/2
zsh        580 omnius   10u   CHR   136,2      0t0     5 /dev/pts/2
termite    774 omnius   10u   CHR     5,2      0t0    22 /dev/ptmx
zsh        779 omnius    0u   CHR   136,3      0t0     6 /dev/pts/3
zsh        779 omnius    1u   CHR   136,3      0t0     6 /dev/pts/3
zsh        779 omnius    2u   CHR   136,3      0t0     6 /dev/pts/3
zsh        779 omnius   10u   CHR   136,3      0t0     6 /dev/pts/3
termite    806 omnius   10u   CHR     5,2      0t0    22 /dev/ptmx
zsh        811 omnius    0u   CHR   136,4      0t0     7 /dev/pts/4
zsh        811 omnius    1u   CHR   136,4      0t0     7 /dev/pts/4
zsh        811 omnius    2u   CHR   136,4      0t0     7 /dev/pts/4
zsh        811 omnius   10u   CHR   136,4      0t0     7 /dev/pts/4
termite    830 omnius   10u   CHR     5,2      0t0    22 /dev/ptmx
zsh        838 omnius    0u   CHR   136,5      0t0     8 /dev/pts/5
zsh        838 omnius    1u   CHR   136,5      0t0     8 /dev/pts/5
zsh        838 omnius    2u   CHR   136,5      0t0     8 /dev/pts/5
zsh        838 omnius   10u   CHR   136,5      0t0     8 /dev/pts/5
termite    842 omnius   10u   CHR     5,2      0t0    22 /dev/ptmx
zsh        847 omnius    0u   CHR   136,6      0t0     9 /dev/pts/6
zsh        847 omnius    1u   CHR   136,6      0t0     9 /dev/pts/6
zsh        847 omnius    2u   CHR   136,6      0t0     9 /dev/pts/6
zsh        847 omnius   10u   CHR   136,6      0t0     9 /dev/pts/6
mpv        851 omnius    0u   CHR   136,6      0t0     9 /dev/pts/6
mpv        851 omnius    1u   CHR   136,6      0t0     9 /dev/pts/6
mpv        851 omnius    2u   CHR   136,6      0t0     9 /dev/pts/6
canto-cur  914 omnius    0u   CHR   136,5      0t0     8 /dev/pts/5
canto-cur  914 omnius    1u   CHR   136,5      0t0     8 /dev/pts/5
termite   1353 omnius   10u   CHR     5,2      0t0    22 /dev/ptmx
weechat   1358 omnius    0u   CHR   136,7      0t0    10 /dev/pts/7
weechat   1358 omnius    1u   CHR   136,7      0t0    10 /dev/pts/7
weechat   1358 omnius    2u   CHR   136,7      0t0    10 /dev/pts/7
termite   1983 omnius   10u   CHR     5,2      0t0    22 /dev/ptmx
zsh       1988 omnius    0u   CHR   136,8      0t0    11 /dev/pts/8
zsh       1988 omnius    1u   CHR   136,8      0t0    11 /dev/pts/8
zsh       1988 omnius    2u   CHR   136,8      0t0    11 /dev/pts/8
zsh       1988 omnius   10u   CHR   136,8      0t0    11 /dev/pts/8
man       1992 omnius    0u   CHR   136,8      0t0    11 /dev/pts/8
man       1992 omnius    1u   CHR   136,8      0t0    11 /dev/pts/8
man       1992 omnius    2u   CHR   136,8      0t0    11 /dev/pts/8
less      2002 omnius    1u   CHR   136,8      0t0    11 /dev/pts/8
less      2002 omnius    2u   CHR   136,8      0t0    11 /dev/pts/8
termite   2096 omnius  cwd    DIR    8,49    16384     1 /run/media/omnius/INTENSO
termite   2096 omnius   10u   CHR     5,2      0t0    22 /dev/ptmx
zsh       2101 omnius  cwd    DIR    8,49    16384     1 /run/media/omnius/INTENSO
zsh       2101 omnius    0u   CHR   136,9      0t0    12 /dev/pts/9
zsh       2101 omnius    1u   CHR   136,9      0t0    12 /dev/pts/9
zsh       2101 omnius    2u   CHR   136,9      0t0    12 /dev/pts/9
zsh       2101 omnius   10u   CHR   136,9      0t0    12 /dev/pts/9
lsof      2105 omnius    0u   CHR   136,4      0t0     7 /dev/pts/4
lsof      2105 omnius    1u   CHR   136,4      0t0     7 /dev/pts/4
lsof      2105 omnius    2u   CHR   136,4      0t0     7 /dev/pts/4
```
The output changed dramatically and not in a good way. The supplied path is a mounted thumb-drive, with just a terminal open at the mountpoint.
It kinda seems the output is now recursive all the way?
Looking back at the discussion in favor of lsof the output looked like [this](https://github.com/dyne/Tomb/issues/220#issuecomment-169093994) which was correct.
Dunno where this comes from. Maybe there is a option to reduce the search, or it is indeed related to kernel

**Comment by Narrat** [comment] 2018-03-15 20:48
lsof doing funny stuff, but fuser is also surprising. Looking good for a switch back to fuser.
I'm now getting results for fuser in /run directories. Would be nice if @fleanegan or others which had the same problem could report their results with fuser.

```
$ fuser -vm /run/media/omnius/INTENSO           
                     BEN.        PID ZUGR.  BEFEHL
/run/media/omnius/INTENSO:
                     root     kernel mount /run/media/omnius/INTENSO
                     omnius     2096 ..c.. termite
                     omnius     2101 ..c.. zsh
                     omnius     2452 ..c.. l3afpad
```
So, going back to `fuser -km <mountpoint>` seems to be a viable option

**Comment by Narrat** [comment] 2018-03-17 14:13
Following the issue on the Arch bugtracker, where got mentioned that there is a new feature in lsof which causes this (+/-E : Linux pseudoterminal endpoint processing).
So it could be disabled, but needs special handling with older lsof versions?
I will look if I can provide a PR later.

**Comment by jaromil** [comment] 2018-03-18 09:20
ACK. thanks! do you know since when (what version of lsof) is this -E flag needed?
so sad they introduced a feature and changed the default...

**Comment by Narrat** [comment] 2018-03-18 12:27
Should be just the latest release 4.90 which was released recently. The previous version 4.89 got released somewhere in 2015.

**Comment by Narrat** [comment] 2018-03-25 21:53
On Arch a patch was added, so the issue should be resolved with 4.90-2.
Upstream also fixed it, but will be part of 4.91, which is hopefully released soon. If so no version check will be necessary.

**Comment by jaromil** [comment] 2018-03-29 06:47
OK so this is a but, but not our bug, and is being fixed in lsof.
Plus it affects only people testing rolling releases.
I guess the best we can do is to not touch anything.

**Comment by Narrat** [comment] 2018-04-22 10:09
@popsUlfr: The general issue is fixed for me. What is your status?

**Comment by popsUlfr** [comment] 2018-04-23 07:17
@Narrat @jaromil 

Fully updated Arch with `lsof-4.91-1` I can confirm that `tomb slam all` does not mass murder my graphical applications anymore :grin:

**Comment by Narrat** [comment] 2020-11-13 18:36
Still worth to add anykind of doc for this behaviour? I would just close this issue as it didn't came back

**Comment by jaromil** [comment] 2020-11-13 20:20
yep lets do that thanks!

**Closed by jaromil** 2020-11-13 20:20 UTC
Labels: discussion, documentation, minor
