### ISSUE TITLE
Download link for a tomb package version changes/breaks on new version

### ISSUE THREAD

**Issue by gregtzar** [dyne/Tomb#346] opened 2019-04-09 22:04 UTC
The naming convention in the tomb filestore places the current version directly in the `https://files.dyne.org/tomb/` directory and then moves it to the `https://files.dyne.org/tomb/old-releases/` directory when a new version is released, breaking the link for scripts which might reference it.

It would be nice to offer a static link for anyone who needs it. One such example is my [docker-tomb](https://github.com/gregtzar/docker-tomb) project which references the latest docker version in the `Dockerfile`. One low friction solution would be to always include the latest release in the `tomb/old-releases` folder as well as the `tomb` folder.

**Comment by jaromil** [comment] 2019-05-31 10:01
Hi! thanks for the advice. I have followed it and the issue is now fixed, see https://files.dyne.org/tomb/releases/ which contains all releases, while latest is linked from base directory. Ciao

**Closed by jaromil** 2019-05-31 10:01 UTC
