### ISSUE TITLE
ERROR nomdc_with_legacy_cipher 152

### ISSUE THREAD

**Issue by amendezcabrera** [dyne/Tomb#334] opened 2018-11-17 21:42 UTC
I can't open one of my encrypted containers because of the next error:

> tomb [D] using pinentry-gtk2
tomb [D] get_lukskey
tomb [D] Created tempfile: /tmp/zsh/1549626126121704613
tomb [D] gpg: datos cifrados 3DES
tomb [D] [GNUPG:] NEED_PASSPHRASE_SYM 2 3 2
tomb [D] gpg: cifrado con 1 frase contraseña
tomb [D] [GNUPG:] BEGIN_DECRYPTION
tomb [D] [GNUPG:] DECRYPTION_COMPLIANCE_MODE 23
tomb [D] [GNUPG:] DECRYPTION_INFO 0 2
tomb [D] [GNUPG:] PLAINTEXT 62 1369073423 tomb.10546.JYbkTu5
tomb [D] [GNUPG:] PLAINTEXT_LENGTH 256
tomb [D] gpg: ATENCIÓN: la intgridad del mensaje no está protegida
tomb [D] gpg: Hint: If this message was created before the year 2003 it is
tomb [D]      likely that this message is legitimate.  This is because back
tomb [D]      then integrity protection was not widely used.
tomb [D] gpg: Use the option '--ignore-mdc-error' to decrypt anyway.
tomb [D] [GNUPG:] ERROR nomdc_with_legacy_cipher 152
tomb [D] gpg: decryption forced to fail!
tomb [D] [GNUPG:] DECRYPTION_FAILED
tomb [D] [GNUPG:] END_DECRYPTION

My Tomb version is 2.5 and the command executed
> tomb open --ignore-swap misdatos.tomb -k misdatos.tomb.key

My Linux kernel version:

> Linux arch 4.19.2-arch1-1-ARCH #1 SMP PREEMPT Tue Nov 13 21:16:19 UTC 2018 x86_64 GNU/Linux

Is there anything I can do in order to open my container? Thank you very much

**Comment by Narrat** [comment] 2018-11-18 23:37
Really old tomb or specific use of 3DES while creating the tomb?
Nevertheless, what I can tell from the log it looks like you hit a depreciation warning from gnupg. It seems 3DES or some part of it is deprecated.
Didn't see a note in the latest gnupg release, so dunno if a temporary downgrade would work. Long time no update on your Arch Linux machine or didn't you open it for a long time?
You could either edit tomb and add the mentioned option to the gpg command or use the manual method for opening a tomb (see readme).
In the long run you want to replace the key for the tomb or create a completely new one.

**Comment by amendezcabrera** [comment] 2018-11-19 08:01
Yes it is a very old tomb I created some years ago, I will try by temporarily downgrading GPG or manually opening my tomb and see if that works, in that case I will create a new tomb with a new key to hold my files and let you know.  Thank you

**Comment by jaromil** [comment] 2018-11-19 11:43
This is one more use-case convincing me that key encryption could be simplified by removing the dependency to gpg.

**Comment by roddhjav** [comment] 2018-11-19 15:39
@jaromil how do you want to manage key encryption if not with gpg?

**Comment by jaromil** [comment] 2018-11-19 16:45
In http://zenroom.dyne.org I have a stable implementation of AES-GCM and AEAD encapsulation wich would provide some advantages:
- binary check (static musl-libc build)
- header authentication
- integrated PBKDF2 (one less binary)
- cleaner and flexible parsing of json headers
- more scriptable functionalities...

**Comment by Narrat** [comment] 2018-11-20 20:49
Dunno if this really is such a bad use-case? It indirectly informed the user, that the key for the tomb isn't secure anymore. Just annoying you cannot directly add options to the gpg call (could be changed).
But if zenroom is such a viable option?

**Comment by jaromil** [comment] 2018-12-06 09:50
I will work on this sometimes soon after Zenroom 1.0 release and provide something integrated you can test, will be pretty minimal. Of course won't remove gpg at all nor aiming to create regressions, just add it as an option / extras.

**Comment by jaromil** [comment] 2020-11-17 11:32
closing as issue is not a bug

**Closed by jaromil** 2020-11-17 11:32 UTC
Labels: discussion, enhancement
